// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = "https://hjiwudojmmrrnmayewmd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhqaXd1ZG9qbW1ycm5tYXlld21kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk5MjYyNjAsImV4cCI6MjA4NTUwMjI2MH0.1HoJCtMDGN26Mfhs59PDr3irNaouZe2qFfMJ7RVMEpE";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  }
);
